### ISSUE TITLE
Crash and non termination issue in the Reconstruct module

### ISSUE THREAD

**Issue by HugoPeters1024** [bgamari/ghc-dump#28] opened 2022-04-18 14:20 UTC
The following source

```haskell
{-# LANGUAGE ExistentialQuantification #-}
{-# LANGUAGE OverloadedStrings #-}
module Main where

import Data.Char

data Step s c = Done | Yield c s | Skip s

data Stream c = forall s. Stream (s -> Step s c) s String

{-# Rules
   "writeUp/readUp erasion"                     readUp . writeUp    = id  ;
   "writeUp/readUp erasion2"         forall xs. readUp (writeUp xs) = xs  ;
#-}


myMap f = writeUp . mapS f . readUp


{-# NOINLINE readUp #-}
readUp :: [a] -> Stream a
readUp s = Stream next s []
    where
        next (c:tl) = Yield c tl
        next []     = Done


{-# NOINLINE writeUp #-}
writeUp :: Stream a -> [a]
writeUp (Stream next s n) = go s
    where go s = case next s of
                   Done -> []
                   Yield c s -> c : go s
                   Skip s -> go s

mapS :: (a -> b) -> Stream a -> Stream b
mapS f (Stream next s n) = Stream next' s n
    where next' s = case next s of
                      Done -> Done
                      Yield x s' -> Yield (f x) s'
                      Skip s' -> Skip s'

bigOp :: [Int] -> [Int]
bigOp = myMap (+1) . myMap (+1) . myMap (+1)

msg = bigOp [0,1,2,3]

main :: IO ()
main = putStrLn "Look at the core!"
```

Causes an error when compiled with the plugin (GHC 9.2.1). It says something about an unknown binding and then gets stuck printing the variables in scopes.

Investigation results:

- The issue is already present in the desugared module (so no fancy optimisations yet)
- Disabling the rewrite rules does not help (like because of they haven't fired at this stage anyway)
- The no online pragmas are not to blame
- ExistentialQuantification is suspect

**Comment by bgamari** [comment] 2022-04-18 14:40
Strangely, this doesn't appear to crash for me. Do you suppose you could attach the affected dump file?

**Comment by HugoPeters1024** [comment] 2022-04-18 14:43
> Strangely, this doesn't appear to crash for me. Do you suppose you could attach the affected dump file?

Yes ofc, here you go https://we.tl/t-qXJljkxX83

**Comment by bgamari** [comment] 2022-04-18 14:53
Oh dear, this is very odd. The same file can be read without any trouble locally:
```
$ git rev-parse HEAD
c264d33624b367ff84e0a299d6605479ae04b07f
$ cabal repl ghc-dump-util
λ> mod <- readDump "/home/ben/code/maintaining/ghc-dump/Main.core.pass0"
λ> mod
Module {moduleName = ModuleName {getModuleName = "Main"}, modulePhase = "Desugared", moduleTopBindings = [NonRecTopBinding (Bndr {unBndr = Binder {binderName = "doubleNo", binderId = BinderId rii, binderIdInfo = IdInfo {idiArity = 0, idiIsOneShot = False, idiUnfolding = CoreUnfolding {unfTemplate = EApp (EApp (EApp (EApp (EApp (EVarGlobal (ExternalName {externalModuleName = ModuleName {getModuleName = "GHC.Base"}, externalName = ".", externalUnique = riP})) (EType (TyConApp (TyCon "Bool" 38) []))) (EType (TyConApp (TyCon "Bool" 38) []))) (EType (TyConApp (TyCon "Bool" 38) []))) (EVarGlobal (ExternalName {externalModuleName = ModuleName {getModuleName = "GHC.Classes"}, externalName = "not", externalUnique = rjU}))) (EVarGlobal (ExternalName {externalModuleName = ModuleName {getModuleName = "GHC.Classes"}, externalName = "not", externalUnique = rjU})), unfIsValue = True, unfIsConLike = True, unfIsWorkFree = True, unfGuidance = "IF_ARGS [] 30 60"}, idiInlinePragma = "", idiOccInfo = OccManyOccs, idiStrictnessSig = "", idiDemandSig = "L", idiCallArity = 0}, binderIdDetails = VanillaId, binderType = FunTy (TyConApp (TyCon "Bool" 38) []) (TyConApp (TyCon "Bool" 38) [])}}) (CoreStats {csTerms = 3, csTypes = 3, csCoercions = 0, csValBinds = 0, csJoinBinds = 0}) (EApp (EApp (EApp (EApp (EApp (EVarGlobal (ExternalName {externalModuleName = ModuleName {getModuleName = "GHC.Base"}, externalName = ".", externalUnique = riP})) (EType (TyConApp (TyCon "Bool" 38) []))) (EType (TyConApp (TyCon "Bool" 38) []))) (EType (TyConApp (TyCon "Bool" 38) []))) (EVarGlobal (ExternalName {externalModuleName = ModuleName {getModuleName = "GHC.Classes"}, externalName = "not", externalUnique = rjU}))) (EVarGlobal (ExternalName {externalModuleName = ModuleName {getModuleName = "GHC.Classes"}, externalName = "not", externalUnique = rjU}))),NonRecTopBinding (Bndr {unBndr = Binder {binderName = "main", binderId = BinderId rij, binderIdInfo = IdInfo {idiArity = 0, idiIsOneShot = False, idiUnfolding = CoreUnfolding {unfTemplate = EApp (EVarGlobal (ExternalName {externalModuleName = ModuleName {getModuleName = "System.IO"}, externalName = "putStrLn", externalUnique = rjM})) (EApp (EVarGlobal (ExternalName {externalModuleName = ModuleName {getModuleName = "GHC.CString"}, externalName = "unpackCString#", externalUnique = 0k})) (ELit (MachStr "Look at the core!"))), unfIsValue = True, unfIsConLike = True, unfIsWorkFree = False, unfGuidance = "IF_ARGS [] 100 60"}, idiInlinePragma = "", idiOccInfo = OccManyOccs, idiStrictnessSig = "", idiDemandSig = "L", idiCallArity = 0}, binderIdDetails = VanillaId, binderType = TyConApp (TyCon "IO" 31Q) [TyConApp (TyCon "()" 40) []]}}) (CoreStats {csTerms = 3, csTypes = 0, csCoercions = 0, csValBinds = 0, csJoinBinds = 0}) (EApp (EVarGlobal (ExternalName {externalModuleName = ModuleName {getModuleName = "System.IO"}, externalName = "putStrLn", externalUnique = rjM})) (EApp (EVarGlobal (ExternalName {externalModuleName = ModuleName {getModuleName = "GHC.CString"}, externalName = "unpackCString#", externalUnique = 0k})) (ELit (MachStr "Look at the core!")))),NonRecTopBinding (Bndr {unBndr = Binder {binderName = "main", binderId = BinderId 01D, binderIdInfo = IdInfo {idiArity = 0, idiIsOneShot = False, idiUnfolding = CoreUnfolding {unfTemplate = EApp (EApp (EVarGlobal (ExternalName {externalModuleName = ModuleName {getModuleName = "GHC.TopHandler"}, externalName = "runMainIO", externalUnique = 01E})) (EType (TyConApp (TyCon "()" 40) []))) (EVarGlobal (ExternalName {externalModuleName = ModuleName {getModuleName = "Main"}, externalName = "main", externalUnique = rij})), unfIsValue = True, unfIsConLike = True, unfIsWorkFree = True, unfGuidance = "IF_ARGS [] 20 60"}, idiInlinePragma = "", idiOccInfo = OccManyOccs, idiStrictnessSig = "", idiDemandSig = "L", idiCallArity = 0}, binderIdDetails = VanillaId, binderType = TyConApp (TyCon "IO" 31Q) [TyConApp (TyCon "()" 40) []]}}) (CoreStats {csTerms = 2, csTypes = 1, csCoercions = 0, csValBinds = 0, csJoinBinds = 0}) (EApp (EApp (EVarGlobal (ExternalName {externalModuleName = ModuleName {getModuleName = "GHC.TopHandler"}, externalName = "runMainIO", externalUnique = 01E})) (EType (TyConApp (TyCon "()" 40) []))) (EVarGlobal (ExternalName {externalModuleName = ModuleName {getModuleName = "Main"}, externalName = "main", externalUnique = rij}))),NonRecTopBinding (Bndr {unBndr = Binder {binderName = "$trModule", binderId = BinderId rik, binderIdInfo = IdInfo {idiArity = 0, idiIsOneShot = False, idiUnfolding = CoreUnfolding {unfTemplate = EApp (EApp (EVarGlobal (ExternalName {externalModuleName = ModuleName {getModuleName = "GHC.Types"}, externalName = "Module", externalUnique = r4})) (EApp (EVarGlobal (ExternalName {externalModuleName = ModuleName {getModuleName = "GHC.Types"}, externalName = "TrNameS", externalUnique = r7})) (ELit (MachStr "main")))) (EApp (EVarGlobal (ExternalName {externalModuleName = ModuleName {getModuleName = "GHC.Types"}, externalName = "TrNameS", externalUnique = r7})) (ELit (MachStr "Main"))), unfIsValue = True, unfIsConLike = True, unfIsWorkFree = True, unfGuidance = "IF_ARGS [] 70 10"}, idiInlinePragma = "", idiOccInfo = OccManyOccs, idiStrictnessSig = "", idiDemandSig = "L", idiCallArity = 0}, binderIdDetails = VanillaId, binderType = TyConApp (TyCon "Module" 622) []}}) (CoreStats {csTerms = 5, csTypes = 0, csCoercions = 0, csValBinds = 0, csJoinBinds = 0}) (EApp (EApp (EVarGlobal (ExternalName {externalModuleName = ModuleName {getModuleName = "GHC.Types"}, externalName = "Module", externalUnique = r4})) (EApp (EVarGlobal (ExternalName {externalModuleName = ModuleName {getModuleName = "GHC.Types"}, externalName = "TrNameS", externalUnique = r7})) (ELit (MachStr "main")))) (EApp (EVarGlobal (ExternalName {externalModuleName = ModuleName {getModuleName = "GHC.Types"}, externalName = "TrNameS", externalUnique = r7})) (ELit (MachStr "Main"))))]}
```

Very odd. @HugoPeters1024, how are you testing this?

**Comment by HugoPeters1024** [comment] 2022-04-18 15:21
I am running a plugin that adds this pass as the very first pass:

```haskell
dumpPass :: Int -> String -> CoreToDo
dumpPass n phase = CoreDoPluginPass phase $ \guts -> do
    dflags <- getDynFlags
    let prefix :: String = showSDocUnsafe (ppr (mg_module guts))
    let fname = coreDumpFile prefix n
    liftIO $ do
        putStrLn fname
        let smodule :: Ast.SModule = Ast.cvtModule dflags phase guts
        BSL.writeFile (fname) $ Ser.serialise smodule
        print (Ast.reconModule smodule)
    pure guts
```

**Comment by HugoPeters1024** [comment] 2022-04-18 15:24
I think I might have sent you the wrong serialized file, this should be the one: https://we.tl/t-dAJbdtTqcw

**Comment by bgamari** [comment] 2022-04-18 15:57
Ahh yes, that reproduces. Very odd that I can't reproduce this with the same source file though.

**Comment by bgamari** [comment] 2022-04-18 17:16
Alright, I can now reproduce this. The minimal reproducer is:
```haskell
{-# LANGUAGE ExistentialQuantification #-}
{-# LANGUAGE OverloadedStrings #-}
module T28 where

import Data.Char

data Step s c = Done | Yield c s | Skip s

data Stream c = forall s. Stream (s -> Step s c) s String

{-# NOINLINE writeUp #-}
writeUp :: Stream a -> [a]
writeUp (Stream next s n) = go s
    where go s = case next s of
                   Done -> []
                   Yield c s -> c : go s
                   Skip s -> go s
```

**Comment by HugoPeters1024** [comment] 2022-04-18 17:19
The last words before failing `TyConApp (TyCon "Typeghc: panic! (the 'impossible' happened)` tell me that it is definitely a type level binder that's to blame. I've traced all binders ever traversed and its not just a scoping issue since the Unique had never been seen before. The word `Typeghc` just before the error seems to suggest that maybe there are some global types bound by ghc that we need to consider?

**Comment by HugoPeters1024** [comment] 2022-04-18 17:21
It seems to me that only the `ForAllTy` case binds type variables but that does leave one wondering how existential types are represented

**Comment by bgamari** [comment] 2022-04-18 17:23
I found and fixed one issue. We failed to add let-bindings into the environment used to reconstruct their RHSs. This would manifest as reconstruction failing on  recursive bindings. How I managed not to find this before now is beyond me:
```patch
diff --git a/ghc-dump-util/src/GhcDump/Reconstruct.hs b/ghc-dump-util/src/GhcDump/Reconstruct.hs
index 302e6e7..928e622 100644
--- a/ghc-dump-util/src/GhcDump/Reconstruct.hs
+++ b/ghc-dump-util/src/GhcDump/Reconstruct.hs
@@ -55,7 +55,7 @@ reconExpr bm (ETyLam b x)     = let b' = reconBinder bm b
 reconExpr bm (ELam b x)       = let b' = reconBinder bm b
                                     bm' = insertBinder b' bm
                                 in ELam b' (reconExpr bm' x)
-reconExpr bm (ELet bs x)      = let bs' = map (bimap (reconBinder bm) (reconExpr bm')) bs
+reconExpr bm (ELet bs x)      = let bs' = map (bimap (reconBinder bm') (reconExpr bm')) bs
                                     bm' = insertBinders (map fst bs') bm
                                 in ELet bs' (reconExpr bm' x)
 reconExpr bm (ECase x b alts) = let b' = reconBinder bm b
```

**Comment by HugoPeters1024** [comment] 2022-04-18 17:25
That's interesting, I was sure it had something to do with `reconType` and would have never looked there. Glad you were able to fix it! :)

**Comment by HugoPeters1024** [comment] 2022-04-18 17:28
Actually, that leads to an infinite loop for me...

**Comment by bgamari** [comment] 2022-04-18 17:30
Indeed I was about to point this out: it turns out that the unfolding itself is recursive, which makes pretty-printing a bit tricky (e.g. will produce infinite output, since each occurrence prints its unfolding, which prints another occurrence, which prints its unfolding, etc.). Perhaps we should only print unfoldings in binding occurrences.

**Comment by HugoPeters1024** [comment] 2022-04-18 17:35
I see the following possibility:

Per (module, pass)
1. Do a renaming pass removing all shadowing (needed for 2)
2. Use a global BinderId -> Binder lookup table

This approach would in some way be needed anyway (at least for efficiency) for my use case where the unfolding is requested on a per term basis interactively

**Comment by bgamari** [comment] 2022-04-18 17:38
@HugoPeters1024 perhaps we should jump on a call for a moment? https://meet.jit.si/ClinicalRebellionsAssumeDeeply

**Comment by bgamari** [comment] 2022-04-18 18:01
I've pushed 91f5f8167529e654d4f6724d3e672ae9d7e7b7ad which fixes the bug here. Moreover, @HugoPeters1024 and I chatted about his issue and we realized that he should probably use the non-reconstructed AST anyways.

**Closed as completed by bgamari** 2022-04-18 18:01 UTC
